services:
  api:
    container_name: dazzle-api
    image: dazzle-api
    build:
      context: .
      target: api
    restart: unless-stopped
    working_dir: /app
    # Only needed on a local machine
    # env_file:
    #   - ./.env
    # volumes:
    #   - storage-data:/app/storage/app/public
    user: "1000"
    # Only needed on a local machine
    # depends_on:
    #   db:
    #     condition: service_healthy
    networks:
      - frontend
      - backend

  admin:
    container_name: dazzle-admin
    image: dazzle-admin
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8000:8080"
    # Only for local development
    # volumes:
    #   - storage-data:/app/public/storage
    depends_on:
      - api
    networks:
      - frontend

# Only for local development
#  db:
#    container_name: dazzle-db
#    image: cgr.dev/chainguard/mariadb
#    restart: unless-stopped
#    env_file:
#      - ./.env
#    environment:
#      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
#      MARIADB_USER: ${DB_USERNAME}
#      MARIADB_PASSWORD: ${DB_PASSWORD}
#      MARIADB_DATABASE: dazzle
#    ports:
#      - "3306:3306"
#    volumes:
#      - mariadbdata:/var/lib/mysql
#    networks:
#      - backend
#    healthcheck:
#      test: mariadb-admin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD
#      start_period: 5s
#      interval: 5s
#      timeout: 5s
#      retries: 50

# Only for local development
# volumes:
#   mariadbdata:
#   storage-data:
networks:
  frontend:
  backend:
