services:
  api:
    container_name: dazzle-api
    restart: unless-stopped
    networks:
      - dazzle-api-and-admin

  admin:
    container_name: dazzle-admin
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - dazzle-api-and-admin

networks:
  dazzle-api-and-admin:
